extends: spectral:oas
formats: [oas3]
rules:
  info-contact:
    severity: error
    message: Info object must have "contact" object.
  info-description:
    severity: error
    message: Info "description" must be present and non-empty string.
  operation-description:
    severity: error
    message: Operation "description" must be present and non-empty string.
  operation-operationId:
    severity: error
    message: Operation must have "operationId".
  operation-tags:
    severity: error
    message: Operation must have non-empty "tags" array.
  operation-operationId-valid-in-url:
    severity: error
    message: operationId must not contain characters that are invalid when used in a URL.
