openapi: 3.0.0
info:
  title: HttpBin GET API
  version: 1.0.0
servers:
  - url: https://httpbin.org/get
paths:
  /ip:
    get:
      operationId: getMessage
      summary: Get Message
      responses:
        '200':
          description: OK