openapi: 3.0.0
info:
  title: HttpBin IP API
  version: 1.0.0
  description: This is Mock API to get Static IP
  contact:
    email: rakesh.kumawat@neosalpha.com
servers:
  - url: https://rakeshkumawat-eval-test.apigee.net
tags:
  - name: ip
paths:
  /httpbin/ip:
    get:
      tags:
        - ip
      responses:
        '200':
          description: OK
