openapi: 3.0.0
info:
  title: HttpBin GET API
  version: 1.0.0
servers:
  - url:	https://rakeshkumawat-eval-test.apigee.net
paths:
  /httpbin/get:
    get:
      operationId: getMessage
      summary: Get Message
      responses:
        '200':
          description: OK
